#ifndef ErrorCode_H
#define ErrorCode_H
#define ERR_STR_INCLURE_ALPHA -1
#define ERR_STR_INCLUDE_SYMBOL -2
#define ERR_STR_CANNOT_BE_EMPTY -3
#define ERR_STR_CANNOT_BE_NULL -4
#define ERR_STR_OBJECT_CANNOT_BE_NULL -5
#define ERR_STR_CANNOT_CONTAIN_INVALID_OPERATOR -6
#define ERR_STR_CANNOT_CONTAIN_INVALID_SYMBOL -7
#define ERR_END_OF_STR_WITHOUT_DOUBLE_QUOTE -8
#define ERR_INTEGER_CANNOT_CONTAIN_SECOND_DECIMAL_POINT -9
#define ERR_INTEGER_CANNOT_CONTAIN_ALPHA -10
#define ERR_BEHIND_EXPONENTIAL_MUST_BE_A_DIGIT -11
#define ERR_INVALID_OCTAL -12
#define ERR_INVALID_HEX -13
/* #define ERR_TEXT_IS_EMPTY 1
#define ERR_NOT_A_NUMBER 2
#define ERR_CANNOT_BE_FLOAT_NUMBER 3
#define ERR_NOT_A_POSITIVE_NUMBER 4 */

void tryCatch();
#endif // TryCatch_H
